import './js/api-service';
import './js/home-page';
import './js/menu';
import './js/kralinskyi';
import './js/iskra';
import './js/auth';
import './js/topic';
import './js/render-categories-list';
import './js/auth';
